// Per-element solid-state crystal structure, keyed by symbol.
// { lattice: <render bucket key>, name: <human label> }. Researched & verified.
const CRYSTALS = {
  "H": {"lattice":"hcp","name":"Hexagonal close-packed (solid H2)"},
  "He": {"lattice":"hcp","name":"Hexagonal close-packed"},
  "Li": {"lattice":"bcc","name":"Body-centred cubic"},
  "Be": {"lattice":"hcp","name":"Hexagonal close-packed"},
  "B": {"lattice":"rhombohedral","name":"Rhombohedral"},
  "C": {"lattice":"graphite","name":"Graphite (hexagonal layers)"},
  "N": {"lattice":"other","name":"Cubic molecular (solid N2)"},
  "O": {"lattice":"other","name":"Monoclinic molecular (solid O2)"},
  "F": {"lattice":"other","name":"Cubic molecular (solid F2)"},
  "Ne": {"lattice":"fcc","name":"Face-centred cubic"},
  "Na": {"lattice":"bcc","name":"Body-centred cubic"},
  "Mg": {"lattice":"hcp","name":"Hexagonal close-packed"},
  "Al": {"lattice":"fcc","name":"Face-centred cubic"},
  "Si": {"lattice":"diamond","name":"Diamond cubic"},
  "P": {"lattice":"other","name":"Orthorhombic (black P)"},
  "S": {"lattice":"orthorhombic","name":"Orthorhombic"},
  "Cl": {"lattice":"orthorhombic","name":"Orthorhombic"},
  "Ar": {"lattice":"fcc","name":"Face-centred cubic"},
  "K": {"lattice":"bcc","name":"Body-centred cubic"},
  "Ca": {"lattice":"fcc","name":"Face-centred cubic"},
  "Sc": {"lattice":"hcp","name":"Hexagonal close-packed"},
  "Ti": {"lattice":"hcp","name":"Hexagonal close-packed"},
  "V": {"lattice":"bcc","name":"Body-centred cubic"},
  "Cr": {"lattice":"bcc","name":"Body-centred cubic"},
  "Mn": {"lattice":"other","name":"Complex cubic (alpha-Mn)"},
  "Fe": {"lattice":"bcc","name":"Body-centred cubic"},
  "Co": {"lattice":"hcp","name":"Hexagonal close-packed"},
  "Ni": {"lattice":"fcc","name":"Face-centred cubic"},
  "Cu": {"lattice":"fcc","name":"Face-centred cubic"},
  "Zn": {"lattice":"hcp","name":"Hexagonal close-packed"},
  "Ga": {"lattice":"orthorhombic","name":"Orthorhombic"},
  "Ge": {"lattice":"diamond","name":"Diamond cubic"},
  "As": {"lattice":"rhombohedral","name":"Rhombohedral"},
  "Se": {"lattice":"hcp","name":"Hexagonal (trigonal chains)"},
  "Br": {"lattice":"orthorhombic","name":"Orthorhombic"},
  "Kr": {"lattice":"fcc","name":"Face-centred cubic"},
  "Rb": {"lattice":"bcc","name":"Body-centred cubic"},
  "Sr": {"lattice":"fcc","name":"Face-centred cubic"},
  "Y": {"lattice":"hcp","name":"Hexagonal close-packed"},
  "Zr": {"lattice":"hcp","name":"Hexagonal close-packed"},
  "Nb": {"lattice":"bcc","name":"Body-centred cubic"},
  "Mo": {"lattice":"bcc","name":"Body-centred cubic"},
  "Tc": {"lattice":"hcp","name":"Hexagonal close-packed"},
  "Ru": {"lattice":"hcp","name":"Hexagonal close-packed"},
  "Rh": {"lattice":"fcc","name":"Face-centred cubic"},
  "Pd": {"lattice":"fcc","name":"Face-centred cubic"},
  "Ag": {"lattice":"fcc","name":"Face-centred cubic"},
  "Cd": {"lattice":"hcp","name":"Hexagonal close-packed"},
  "In": {"lattice":"tetragonal","name":"Tetragonal"},
  "Sn": {"lattice":"diamond","name":"Diamond cubic (grey tin)"},
  "Sb": {"lattice":"rhombohedral","name":"Rhombohedral"},
  "Te": {"lattice":"hcp","name":"Hexagonal (trigonal chains)"},
  "I": {"lattice":"orthorhombic","name":"Orthorhombic"},
  "Xe": {"lattice":"fcc","name":"Face-centred cubic"},
  "Cs": {"lattice":"bcc","name":"Body-centred cubic"},
  "Ba": {"lattice":"bcc","name":"Body-centred cubic"},
  "La": {"lattice":"dhcp","name":"Double hexagonal close-packed"},
  "Ce": {"lattice":"fcc","name":"Face-centred cubic"},
  "Pr": {"lattice":"dhcp","name":"Double hexagonal close-packed"},
  "Nd": {"lattice":"dhcp","name":"Double hexagonal close-packed"},
  "Pm": {"lattice":"dhcp","name":"Double hexagonal close-packed"},
  "Sm": {"lattice":"rhombohedral","name":"Rhombohedral (Sm-type)"},
  "Eu": {"lattice":"bcc","name":"Body-centred cubic"},
  "Gd": {"lattice":"hcp","name":"Hexagonal close-packed"},
  "Tb": {"lattice":"hcp","name":"Hexagonal close-packed"},
  "Dy": {"lattice":"hcp","name":"Hexagonal close-packed"},
  "Ho": {"lattice":"hcp","name":"Hexagonal close-packed"},
  "Er": {"lattice":"hcp","name":"Hexagonal close-packed"},
  "Tm": {"lattice":"hcp","name":"Hexagonal close-packed"},
  "Yb": {"lattice":"fcc","name":"Face-centred cubic"},
  "Lu": {"lattice":"hcp","name":"Hexagonal close-packed"},
  "Hf": {"lattice":"hcp","name":"Hexagonal close-packed"},
  "Ta": {"lattice":"bcc","name":"Body-centred cubic"},
  "W": {"lattice":"bcc","name":"Body-centred cubic"},
  "Re": {"lattice":"hcp","name":"Hexagonal close-packed"},
  "Os": {"lattice":"hcp","name":"Hexagonal close-packed"},
  "Ir": {"lattice":"fcc","name":"Face-centred cubic"},
  "Pt": {"lattice":"fcc","name":"Face-centred cubic"},
  "Au": {"lattice":"fcc","name":"Face-centred cubic"},
  "Hg": {"lattice":"rhombohedral","name":"Rhombohedral (solid)"},
  "Tl": {"lattice":"hcp","name":"Hexagonal close-packed"},
  "Pb": {"lattice":"fcc","name":"Face-centred cubic"},
  "Bi": {"lattice":"rhombohedral","name":"Rhombohedral"},
  "Po": {"lattice":"simple-cubic","name":"Simple cubic"},
  "At": {"lattice":"other","name":"Unknown / predicted"},
  "Rn": {"lattice":"fcc","name":"Face-centred cubic"},
  "Fr": {"lattice":"bcc","name":"Body-centred cubic"},
  "Ra": {"lattice":"bcc","name":"Body-centred cubic"},
  "Ac": {"lattice":"fcc","name":"Face-centred cubic"},
  "Th": {"lattice":"fcc","name":"Face-centred cubic"},
  "Pa": {"lattice":"tetragonal","name":"Tetragonal"},
  "U": {"lattice":"orthorhombic","name":"Orthorhombic"},
  "Np": {"lattice":"orthorhombic","name":"Orthorhombic"},
  "Pu": {"lattice":"monoclinic","name":"Monoclinic"},
  "Am": {"lattice":"dhcp","name":"Double hexagonal close-packed"},
  "Cm": {"lattice":"dhcp","name":"Double hexagonal close-packed"},
  "Bk": {"lattice":"dhcp","name":"Double hexagonal close-packed"},
  "Cf": {"lattice":"dhcp","name":"Double hexagonal close-packed"},
  "Es": {"lattice":"fcc","name":"Face-centred cubic"},
  "Fm": {"lattice":"other","name":"Unknown / predicted"},
  "Md": {"lattice":"other","name":"Unknown / predicted"},
  "No": {"lattice":"other","name":"Unknown / predicted"},
  "Lr": {"lattice":"hcp","name":"Hexagonal close-packed (predicted)"},
  "Rf": {"lattice":"hcp","name":"Hexagonal close-packed (predicted)"},
  "Db": {"lattice":"bcc","name":"Body-centred cubic (predicted)"},
  "Sg": {"lattice":"bcc","name":"Body-centred cubic (predicted)"},
  "Bh": {"lattice":"hcp","name":"Hexagonal close-packed (predicted)"},
  "Hs": {"lattice":"hcp","name":"Hexagonal close-packed (predicted)"},
  "Mt": {"lattice":"fcc","name":"Face-centred cubic (predicted)"},
  "Ds": {"lattice":"bcc","name":"Body-centred cubic (predicted)"},
  "Rg": {"lattice":"bcc","name":"Body-centred cubic (predicted)"},
  "Cn": {"lattice":"hcp","name":"Hexagonal close-packed (predicted)"},
  "Nh": {"lattice":"hcp","name":"Hexagonal close-packed (predicted)"},
  "Fl": {"lattice":"fcc","name":"Face-centred cubic (predicted)"},
  "Mc": {"lattice":"other","name":"Unknown / predicted"},
  "Lv": {"lattice":"other","name":"Unknown / predicted"},
  "Ts": {"lattice":"other","name":"Unknown / predicted"},
  "Og": {"lattice":"fcc","name":"Face-centred cubic (predicted)"}
};
