// How each element is most commonly found on Earth, with a structural spec
// for a 2D ball-and-stick diagram. Keyed by symbol. Researched & verified.
const FORMS = {
  "H": {"occursAs":"As water (H2O) covering Earth's surface and bound in minerals.","formula":"H2O","shape":"bent3","center":"O","ligand":"H","bond":1},
  "He": {"occursAs":"As an inert monatomic gas (He), trapped in natural gas deposits.","formula":"He","shape":"monatomic","center":"He","ligand":"","bond":0},
  "Li": {"occursAs":"In silicate ores like spodumene (LiAlSi2O6) and brines.","formula":"LiAlSi2O6","shape":"octahedral","center":"Li","ligand":"O","bond":0},
  "Be": {"occursAs":"In the silicate mineral beryl (Be3Al2Si6O18).","formula":"Be3Al2Si6O18","shape":"tetrahedral","center":"Be","ligand":"O","bond":0},
  "B": {"occursAs":"As borate minerals such as borax (Na2B4O7) ore.","formula":"B2O3","shape":"trigonal","center":"B","ligand":"O","bond":1},
  "C": {"occursAs":"As atmospheric carbon dioxide (CO2) and carbonate rocks.","formula":"CO2","shape":"linear3","center":"C","ligand":"O","bond":2},
  "N": {"occursAs":"As diatomic nitrogen gas (N2), 78% of the atmosphere.","formula":"N2","shape":"diatomic","center":"N","ligand":"N","bond":3},
  "O": {"occursAs":"As diatomic oxygen gas (O2) and bound in oxide rocks.","formula":"O2","shape":"diatomic","center":"O","ligand":"O","bond":2},
  "F": {"occursAs":"In the mineral fluorite (CaF2); free F2 does not occur.","formula":"F2","shape":"diatomic","center":"F","ligand":"F","bond":1},
  "Ne": {"occursAs":"As an inert monatomic gas (Ne) in trace atmospheric amounts.","formula":"Ne","shape":"monatomic","center":"Ne","ligand":"","bond":0},
  "Na": {"occursAs":"As rock salt, sodium chloride (NaCl), in seawater and halite.","formula":"NaCl","shape":"rocksalt","center":"Na","ligand":"Cl","bond":0},
  "Mg": {"occursAs":"As carbonate and silicate ores; magnesite (MgCO3) and dolomite.","formula":"MgCO3","shape":"octahedral","center":"Mg","ligand":"O","bond":0},
  "Al": {"occursAs":"As bauxite ore, mainly aluminium oxide (Al2O3) hydrates.","formula":"Al2O3","shape":"octahedral","center":"Al","ligand":"O","bond":0},
  "Si": {"occursAs":"As silica and silicates; quartz is silicon dioxide (SiO2).","formula":"SiO2","shape":"tetrahedral","center":"Si","ligand":"O","bond":1},
  "P": {"occursAs":"As phosphate minerals like apatite, the phosphate ion (PO4).","formula":"PO4","shape":"tetrahedral","center":"P","ligand":"O","bond":1},
  "S": {"occursAs":"As native sulfur, crown-shaped S8 rings near volcanic vents.","formula":"S8","shape":"ring8","center":"S","ligand":"S","bond":1},
  "Cl": {"occursAs":"As chloride in rock salt (NaCl) and seawater; free Cl2 rare.","formula":"Cl2","shape":"diatomic","center":"Cl","ligand":"Cl","bond":1},
  "Ar": {"occursAs":"As an inert monatomic gas (Ar), about 1% of the atmosphere.","formula":"Ar","shape":"monatomic","center":"Ar","ligand":"","bond":0},
  "K": {"occursAs":"As potassium chloride (KCl) in sylvite and other evaporites.","formula":"KCl","shape":"rocksalt","center":"K","ligand":"Cl","bond":0},
  "Ca": {"occursAs":"As limestone and marble, calcium carbonate (CaCO3).","formula":"CaCO3","shape":"octahedral","center":"Ca","ligand":"O","bond":0},
  "Sc": {"occursAs":"Dispersed in oxide and silicate minerals as scandium oxide (Sc2O3).","formula":"Sc2O3","shape":"octahedral","center":"Sc","ligand":"O","bond":0},
  "Ti": {"occursAs":"As oxide ores rutile (TiO2) and ilmenite (FeTiO3).","formula":"TiO2","shape":"octahedral","center":"Ti","ligand":"O","bond":0},
  "V": {"occursAs":"In oxide and vanadate ores as vanadium oxide (V2O5).","formula":"V2O5","shape":"octahedral","center":"V","ligand":"O","bond":0},
  "Cr": {"occursAs":"As chromite ore (FeCr2O4), a chromium oxide spinel.","formula":"Cr2O3","shape":"octahedral","center":"Cr","ligand":"O","bond":0},
  "Mn": {"occursAs":"As pyrolusite ore, manganese dioxide (MnO2).","formula":"MnO2","shape":"octahedral","center":"Mn","ligand":"O","bond":0},
  "Fe": {"occursAs":"As iron-oxide ores hematite (Fe2O3) and magnetite (Fe3O4).","formula":"Fe2O3","shape":"octahedral","center":"Fe","ligand":"O","bond":0},
  "Co": {"occursAs":"In sulfide and arsenide ores; recovered as cobalt oxide (CoO).","formula":"CoO","shape":"octahedral","center":"Co","ligand":"O","bond":0},
  "Ni": {"occursAs":"In sulfide ore pentlandite and laterite oxide (NiO) ores.","formula":"NiO","shape":"octahedral","center":"Ni","ligand":"O","bond":0},
  "Cu": {"occursAs":"Often as native copper (Cu) and in sulfide ores like chalcopyrite.","formula":"Cu","shape":"lattice","center":"Cu","ligand":"Cu","bond":0},
  "Zn": {"occursAs":"As sphalerite, zinc sulfide (ZnS), the main zinc ore.","formula":"ZnS","shape":"tetrahedral","center":"Zn","ligand":"S","bond":0},
  "Ga": {"occursAs":"Dispersed in bauxite and zinc ores as gallium oxide (Ga2O3).","formula":"Ga2O3","shape":"octahedral","center":"Ga","ligand":"O","bond":0},
  "Ge": {"occursAs":"Dispersed in zinc sulfide ores as germanium dioxide (GeO2).","formula":"GeO2","shape":"tetrahedral","center":"Ge","ligand":"O","bond":1},
  "As": {"occursAs":"As sulfide ores, chiefly arsenopyrite (FeAsS) and realgar.","formula":"As2O3","shape":"trigonal","center":"As","ligand":"O","bond":1},
  "Se": {"occursAs":"As trace selenide in sulfide ores; native selenium chains (Se8).","formula":"Se8","shape":"ring8","center":"Se","ligand":"Se","bond":1},
  "Br": {"occursAs":"As bromide salts dissolved in seawater and brine deposits.","formula":"Br2","shape":"diatomic","center":"Br","ligand":"Br","bond":1},
  "Kr": {"occursAs":"As an inert monatomic gas (Kr) in trace atmospheric amounts.","formula":"Kr","shape":"monatomic","center":"Kr","ligand":"","bond":0},
  "Rb": {"occursAs":"Dispersed in potassium minerals; as rubidium chloride (RbCl).","formula":"RbCl","shape":"rocksalt","center":"Rb","ligand":"Cl","bond":0},
  "Sr": {"occursAs":"As celestine (SrSO4) and strontianite carbonate (SrCO3).","formula":"SrCO3","shape":"octahedral","center":"Sr","ligand":"O","bond":0},
  "Y": {"occursAs":"In phosphate and silicate rare-earth ores as yttrium oxide (Y2O3).","formula":"Y2O3","shape":"octahedral","center":"Y","ligand":"O","bond":0},
  "Zr": {"occursAs":"As zircon, zirconium silicate (ZrSiO4), in beach sands.","formula":"ZrSiO4","shape":"octahedral","center":"Zr","ligand":"O","bond":0},
  "Nb": {"occursAs":"In oxide ores pyrochlore and columbite as niobium oxide (Nb2O5).","formula":"Nb2O5","shape":"octahedral","center":"Nb","ligand":"O","bond":0},
  "Mo": {"occursAs":"As molybdenite, molybdenum disulfide (MoS2).","formula":"MoS2","shape":"octahedral","center":"Mo","ligand":"S","bond":0},
  "Tc": {"occursAs":"Essentially absent in nature; traces as oxide (TcO2) in uranium ores.","formula":"TcO2","shape":"octahedral","center":"Tc","ligand":"O","bond":0},
  "Ru": {"occursAs":"As native platinum-group metal alloys; native ruthenium (Ru).","formula":"Ru","shape":"lattice","center":"Ru","ligand":"Ru","bond":0},
  "Rh": {"occursAs":"As a native platinum-group metal in placer and sulfide ores (Rh).","formula":"Rh","shape":"lattice","center":"Rh","ligand":"Rh","bond":0},
  "Pd": {"occursAs":"As a native platinum-group metal (Pd) and in nickel sulfide ores.","formula":"Pd","shape":"lattice","center":"Pd","ligand":"Pd","bond":0},
  "Ag": {"occursAs":"As native silver (Ag) and in sulfide ores like argentite.","formula":"Ag","shape":"lattice","center":"Ag","ligand":"Ag","bond":0},
  "Cd": {"occursAs":"As greenockite (CdS), found alongside zinc sulfide ores.","formula":"CdS","shape":"tetrahedral","center":"Cd","ligand":"S","bond":0},
  "In": {"occursAs":"Dispersed in zinc sulfide ores as indium oxide (In2O3).","formula":"In2O3","shape":"octahedral","center":"In","ligand":"O","bond":0},
  "Sn": {"occursAs":"As cassiterite, tin dioxide (SnO2), the chief tin ore.","formula":"SnO2","shape":"octahedral","center":"Sn","ligand":"O","bond":0},
  "Sb": {"occursAs":"As stibnite, antimony sulfide (Sb2S3), the main antimony ore.","formula":"Sb2O3","shape":"trigonal","center":"Sb","ligand":"O","bond":1},
  "Te": {"occursAs":"As metal tellurides and trace native tellurium (Te) in gold ores.","formula":"TeO2","shape":"tetrahedral","center":"Te","ligand":"O","bond":1},
  "I": {"occursAs":"As iodide and iodate in brines and Chilean caliche deposits.","formula":"I2","shape":"diatomic","center":"I","ligand":"I","bond":1},
  "Xe": {"occursAs":"As an inert monatomic gas (Xe) in trace atmospheric amounts.","formula":"Xe","shape":"monatomic","center":"Xe","ligand":"","bond":0},
  "Cs": {"occursAs":"In the silicate ore pollucite; as caesium chloride (CsCl).","formula":"CsCl","shape":"rocksalt","center":"Cs","ligand":"Cl","bond":0},
  "Ba": {"occursAs":"As barite, barium sulfate (BaSO4), the main barium ore.","formula":"BaSO4","shape":"octahedral","center":"Ba","ligand":"O","bond":0},
  "La": {"occursAs":"In monazite and bastnasite rare-earth ores as oxide (La2O3).","formula":"La2O3","shape":"octahedral","center":"La","ligand":"O","bond":0},
  "Ce": {"occursAs":"In bastnasite and monazite ores as cerium oxide (CeO2).","formula":"CeO2","shape":"octahedral","center":"Ce","ligand":"O","bond":0},
  "Pr": {"occursAs":"In monazite and bastnasite rare-earth ores as oxide (Pr2O3).","formula":"Pr2O3","shape":"octahedral","center":"Pr","ligand":"O","bond":0},
  "Nd": {"occursAs":"As the sesquioxide Nd2O3 in monazite and bastnasite ores.","formula":"Nd2O3","shape":"octahedral","center":"Nd","ligand":"O","bond":0},
  "Pm": {"occursAs":"Synthetic — does not occur naturally.","formula":"Pm","shape":"monatomic","center":"Pm","ligand":"","bond":0},
  "Sm": {"occursAs":"As the sesquioxide Sm2O3 in monazite and bastnasite ores.","formula":"Sm2O3","shape":"octahedral","center":"Sm","ligand":"O","bond":0},
  "Eu": {"occursAs":"As oxide Eu2O3 within monazite and bastnasite rare-earth ores.","formula":"Eu2O3","shape":"octahedral","center":"Eu","ligand":"O","bond":0},
  "Gd": {"occursAs":"As the sesquioxide Gd2O3 in monazite and bastnasite ores.","formula":"Gd2O3","shape":"octahedral","center":"Gd","ligand":"O","bond":0},
  "Tb": {"occursAs":"As oxide Tb2O3 within monazite and bastnasite rare-earth ores.","formula":"Tb2O3","shape":"octahedral","center":"Tb","ligand":"O","bond":0},
  "Dy": {"occursAs":"As the sesquioxide Dy2O3 in monazite and xenotime ores.","formula":"Dy2O3","shape":"octahedral","center":"Dy","ligand":"O","bond":0},
  "Ho": {"occursAs":"As oxide Ho2O3 within monazite and xenotime rare-earth ores.","formula":"Ho2O3","shape":"octahedral","center":"Ho","ligand":"O","bond":0},
  "Er": {"occursAs":"As the sesquioxide Er2O3 in monazite and xenotime ores.","formula":"Er2O3","shape":"octahedral","center":"Er","ligand":"O","bond":0},
  "Tm": {"occursAs":"As oxide Tm2O3 within monazite and xenotime rare-earth ores.","formula":"Tm2O3","shape":"octahedral","center":"Tm","ligand":"O","bond":0},
  "Yb": {"occursAs":"As the sesquioxide Yb2O3 in monazite and xenotime ores.","formula":"Yb2O3","shape":"octahedral","center":"Yb","ligand":"O","bond":0},
  "Lu": {"occursAs":"As oxide Lu2O3 within monazite and xenotime rare-earth ores.","formula":"Lu2O3","shape":"octahedral","center":"Lu","ligand":"O","bond":0},
  "Hf": {"occursAs":"As the silicate HfSiO4, substituting for zirconium in zircon.","formula":"HfO2","shape":"octahedral","center":"Hf","ligand":"O","bond":0},
  "Ta": {"occursAs":"As oxide Ta2O5 in tantalite and columbite ores.","formula":"Ta2O5","shape":"octahedral","center":"Ta","ligand":"O","bond":0},
  "W": {"occursAs":"As tungstate in scheelite and wolframite; oxide WO3.","formula":"WO3","shape":"octahedral","center":"W","ligand":"O","bond":0},
  "Re": {"occursAs":"As trace sulfide substituting for molybdenum in molybdenite.","formula":"ReS2","shape":"octahedral","center":"Re","ligand":"S","bond":0},
  "Os": {"occursAs":"As native metal alloyed with platinum and iridium.","formula":"Os","shape":"lattice","center":"Os","ligand":"","bond":0},
  "Ir": {"occursAs":"As native metal alloyed with platinum and osmium.","formula":"Ir","shape":"lattice","center":"Ir","ligand":"","bond":0},
  "Pt": {"occursAs":"As native metal in placer deposits and platinum ores.","formula":"Pt","shape":"lattice","center":"Pt","ligand":"","bond":0},
  "Au": {"occursAs":"As native metal in veins and placer deposits.","formula":"Au","shape":"lattice","center":"Au","ligand":"","bond":0},
  "Hg": {"occursAs":"As the sulfide cinnabar HgS, its chief ore.","formula":"HgS","shape":"diatomic","center":"Hg","ligand":"S","bond":1},
  "Tl": {"occursAs":"As trace sulfide in copper, lead and zinc ores.","formula":"Tl2S","shape":"diatomic","center":"Tl","ligand":"S","bond":1},
  "Pb": {"occursAs":"As the sulfide galena PbS, its primary ore.","formula":"PbS","shape":"rocksalt","center":"Pb","ligand":"S","bond":0},
  "Bi": {"occursAs":"As native metal or the sulfide bismuthinite Bi2S3.","formula":"Bi2S3","shape":"cluster","center":"Bi","ligand":"S","bond":0},
  "Po": {"occursAs":"Occurs only as a trace decay product in uranium ores.","formula":"Po","shape":"monatomic","center":"Po","ligand":"","bond":0},
  "At": {"occursAs":"Occurs only as a fleeting trace from uranium and thorium decay.","formula":"At","shape":"monatomic","center":"At","ligand":"","bond":0},
  "Rn": {"occursAs":"A trace radioactive gas from radium decay in rocks.","formula":"Rn","shape":"monatomic","center":"Rn","ligand":"","bond":0},
  "Fr": {"occursAs":"Occurs only as a fleeting trace from actinium decay in uranium ores.","formula":"Fr","shape":"monatomic","center":"Fr","ligand":"","bond":0},
  "Ra": {"occursAs":"Occurs only as a trace decay product in uranium and thorium ores.","formula":"Ra","shape":"monatomic","center":"Ra","ligand":"","bond":0},
  "Ac": {"occursAs":"Occurs only as a trace decay product in uranium ores.","formula":"Ac","shape":"monatomic","center":"Ac","ligand":"","bond":0},
  "Th": {"occursAs":"As the oxide thorianite ThO2, mainly in monazite sands.","formula":"ThO2","shape":"octahedral","center":"Th","ligand":"O","bond":0},
  "Pa": {"occursAs":"Occurs only as a trace decay product in uranium ores.","formula":"Pa","shape":"monatomic","center":"Pa","ligand":"","bond":0},
  "U": {"occursAs":"As the oxide uraninite (pitchblende) UO2.","formula":"UO2","shape":"octahedral","center":"U","ligand":"O","bond":0},
  "Np": {"occursAs":"Synthetic — does not occur naturally.","formula":"Np","shape":"monatomic","center":"Np","ligand":"","bond":0},
  "Pu": {"occursAs":"Synthetic — does not occur naturally.","formula":"Pu","shape":"monatomic","center":"Pu","ligand":"","bond":0},
  "Am": {"occursAs":"Synthetic — does not occur naturally.","formula":"Am","shape":"monatomic","center":"Am","ligand":"","bond":0},
  "Cm": {"occursAs":"Synthetic — does not occur naturally.","formula":"Cm","shape":"monatomic","center":"Cm","ligand":"","bond":0},
  "Bk": {"occursAs":"Synthetic — does not occur naturally.","formula":"Bk","shape":"monatomic","center":"Bk","ligand":"","bond":0},
  "Cf": {"occursAs":"Synthetic — does not occur naturally.","formula":"Cf","shape":"monatomic","center":"Cf","ligand":"","bond":0},
  "Es": {"occursAs":"Synthetic — does not occur naturally.","formula":"Es","shape":"monatomic","center":"Es","ligand":"","bond":0},
  "Fm": {"occursAs":"Synthetic — does not occur naturally.","formula":"Fm","shape":"monatomic","center":"Fm","ligand":"","bond":0},
  "Md": {"occursAs":"Synthetic — does not occur naturally.","formula":"Md","shape":"monatomic","center":"Md","ligand":"","bond":0},
  "No": {"occursAs":"Synthetic — does not occur naturally.","formula":"No","shape":"monatomic","center":"No","ligand":"","bond":0},
  "Lr": {"occursAs":"Synthetic — does not occur naturally.","formula":"Lr","shape":"monatomic","center":"Lr","ligand":"","bond":0},
  "Rf": {"occursAs":"Synthetic — does not occur naturally.","formula":"Rf","shape":"monatomic","center":"Rf","ligand":"","bond":0},
  "Db": {"occursAs":"Synthetic — does not occur naturally.","formula":"Db","shape":"monatomic","center":"Db","ligand":"","bond":0},
  "Sg": {"occursAs":"Synthetic — does not occur naturally.","formula":"Sg","shape":"monatomic","center":"Sg","ligand":"","bond":0},
  "Bh": {"occursAs":"Synthetic — does not occur naturally.","formula":"Bh","shape":"monatomic","center":"Bh","ligand":"","bond":0},
  "Hs": {"occursAs":"Synthetic — does not occur naturally.","formula":"Hs","shape":"monatomic","center":"Hs","ligand":"","bond":0},
  "Mt": {"occursAs":"Synthetic — does not occur naturally.","formula":"Mt","shape":"monatomic","center":"Mt","ligand":"","bond":0},
  "Ds": {"occursAs":"Synthetic — does not occur naturally.","formula":"Ds","shape":"monatomic","center":"Ds","ligand":"","bond":0},
  "Rg": {"occursAs":"Synthetic — does not occur naturally.","formula":"Rg","shape":"monatomic","center":"Rg","ligand":"","bond":0},
  "Cn": {"occursAs":"Synthetic — does not occur naturally.","formula":"Cn","shape":"monatomic","center":"Cn","ligand":"","bond":0},
  "Nh": {"occursAs":"Synthetic — does not occur naturally.","formula":"Nh","shape":"monatomic","center":"Nh","ligand":"","bond":0},
  "Fl": {"occursAs":"Synthetic — does not occur naturally.","formula":"Fl","shape":"monatomic","center":"Fl","ligand":"","bond":0},
  "Mc": {"occursAs":"Synthetic — does not occur naturally.","formula":"Mc","shape":"monatomic","center":"Mc","ligand":"","bond":0},
  "Lv": {"occursAs":"Synthetic — does not occur naturally.","formula":"Lv","shape":"monatomic","center":"Lv","ligand":"","bond":0},
  "Ts": {"occursAs":"Synthetic — does not occur naturally.","formula":"Ts","shape":"monatomic","center":"Ts","ligand":"","bond":0},
  "Og": {"occursAs":"Synthetic — does not occur naturally.","formula":"Og","shape":"monatomic","center":"Og","ligand":"","bond":0}
};
